FROM python:3.9.2-buster

COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR /app

ENTRYPOINT [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload" ]
